import React from "react";
import './FooterPage.css';

class FooterPage extends React.Component {
    render() {
        return (
            <div className="Footnote">
                <div className="FooterInfo">
                <p><i>*This is a prototype of Grubhub generated by Madhu Prasanna Kalluraya as part of CMPE 273 Course at San Jose State University. This is purely for academic purposes</i></p>
                </div>
            </div>
        )
    }
}

export default FooterPage;